name: CI
on: 
  schedule:
    - cron: '1 * * * *'
jobs:
  copyBot:
    runs-on: ubuntu-lastest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
